### ISSUE TITLE
Create data models for SQL

### ISSUE THREAD

**Issue by alang2002** [Unit9Group/Unit9API#1]
We need data points for our API first before we can create wireframes for the front end.
Our project is based on cars. Here are the three models we had in mind:

Web API models
Car
-    Name
-    Make
-    Year
-    Color
-    Type (Sedan, SUV, Minivan, Hatchback, etc.)

Truck

-    Name
-    Make
-    Year
-    Color
-    Horsepower

Motorcycle
-    Name
-    Make
-    Year
-    Color
- ?

**Comment by bretinator** [comment]
All three models added
